ruby "2.6.2"
source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "pg", "~> 0.18"
gem "puma", "~> 3.7"
gem "rails", "~> 5.1.4"

gem "acts_as_tenant"
gem "aws-sdk-s3"
gem "brakeman"
gem "deep_cloneable", "~> 2.4.0"
gem "devise"
gem "down"
gem "graphql"
gem "kaminari"
gem "lograge"
gem "omniauth-google-oauth2"
gem "pundit"
gem "rack-cors"
gem "redis-rails", "~> 5"
gem "resque"
gem "resque-scheduler"
gem "rest-client"
gem "rollbar"
gem "rubocop"
# changed to support the EU endpoint. https://github.com/the-refinery/sparkpost_rails/pull/58
gem "sparkpost_rails", github: "dsgh/sparkpost_rails", branch: "custom-api-endpoint"
gem "stripe"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "faker"
  gem "pry"
  gem "pry-byebug"
end

group :development do
  gem "dotenv-rails"
  gem "letter_opener"
  gem "listen", ">= 3.0.5", "< 3.2"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

group :test do
  gem "database_cleaner"
  gem "minitest", "5.10.3" # https://stackoverflow.com/questions/48229515/rails-minitest-crashing-when-tests-fail
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
