ruby "2.4.3"
source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "pg", "~> 0.18"
gem "puma", "~> 3.7"
gem "rails", "~> 5.1.4"

gem "aws-sdk-s3"
gem "brakeman"
gem "devise"
gem "faker"
gem "graphlient"
gem "graphql"
gem "graphql-errors"
gem "hubspot-ruby"
gem "pundit"
gem "rack-cors"
gem "rubocop"
gem "shopify_api"
gem "sparkpost_rails", github: "dsgh/sparkpost_rails", branch: "custom-api-endpoint" # changed to support the EU endpoint. https://github.com/the-refinery/sparkpost_rails/pull/58
gem "stripe"
gem "tiddle"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
end

group :development do
  gem "dotenv-rails"
  gem "letter_opener"
  gem "listen", ">= 3.0.5", "< 3.2"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
