AllCops:
  Include:
    - "**/Gemfile"
    - "**/*.rb"
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
