AllCops:
  Include:
    - Rakefile
    - config.ru
    - "**/Gemfile"
    - "**/*.rake"
    - "**/*.gemspec"
    - "**/*.rb"
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - script/**/*
    - public/**/*
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/ClassStructure:
  Enabled: true

Rails:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods: ["authorize", "desc", "raise", "redirect_to", "render", "require", "require_relative", "run", "ruby", "source", "yield", "gem", "has_many", "head"]

Style/MultilineMethodSignature:
  Enabled: true
