import {
  __spread,
  Children,
  cloneElement,
  Component,
  createClass,
  createElement,
  createFactory,
  DOM,
  findDOMNode,
  isValidElement,
  PropTypes,
  PureComponent,
  render,
  unmountComponentAtNode,
  unstable_renderSubtreeIntoContainer,
  version,
} from 'preact-compat'
import { createContext } from 'preact-context'

export {
  version,
  DOM,
  PropTypes,
  Children,
  render,
  createClass,
  createFactory,
  createElement,
  cloneElement,
  isValidElement,
  findDOMNode,
  unmountComponentAtNode,
  Component,
  PureComponent,
  unstable_renderSubtreeIntoContainer,
  __spread,
  createContext,
}
export default {
  __spread,
  Children,
  cloneElement,
  Component,
  createClass,
  createContext,
  createElement,
  createFactory,
  DOM,
  findDOMNode,
  isValidElement,
  PropTypes,
  PureComponent,
  render,
  unmountComponentAtNode,
  unstable_renderSubtreeIntoContainer,
  version,
}
